import { FaMobileAlt } from "react-icons/fa";
import {
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiBootstrap,
  SiAxios,
  SiReactquery,
  SiRedux,
  SiGit,
  SiGithub,
  SiNpm,
  SiReactrouter,
  SiFramer,
} from "react-icons/si";

export const techLogos = [
  { node: <SiReact size={40}/>, title: "React", bgColor: "bg-cyan-500", neon: "#06b6d4" },
  // { node: <SiNextdotjs size={40}/>, title: "Next.js", bgColor: "bg-black", neon: "#a1a1aa" },
  { node: <SiTailwindcss size={40}/>, title: "Tailwind CSS", bgColor: "bg-sky-400", neon: "#38bdf8" },
  { node: <SiJavascript size={40}/>, title: "Javascript", bgColor: "bg-yellow-400", neon: "#facc15" },
  { node: <SiTypescript size={40}/>, title: "TypeScript", bgColor: "bg-blue-600", neon: "#2563eb" },
  { node: <SiHtml5 size={40}/>, title: "HTML5", bgColor: "bg-orange-600", neon: "#ea580c" },
  { node: <SiCss size={40}/>, title: "CSS3", bgColor: "bg-blue-500", neon: "#3b82f6" },
  { node: <SiBootstrap size={40}/>, title: "Bootstrap", bgColor: "bg-purple-600", neon: "#9333ea" },
  { node: <SiReactquery size={40}/>, title: "React Query", bgColor: "bg-red-500", neon: "#ef4444" },
  { node: <SiAxios size={40}/>, title: "Axios", bgColor: "bg-indigo-500", neon: "#6366f1" },
  { node: <SiRedux size={40}/>, title: "Redux", bgColor: "bg-purple-500", neon: "#a855f7" },
  { node: <SiGit size={40}/>, title: "Git", bgColor: "bg-orange-500", neon: "#f97316" },
  { node: <SiGithub size={40}/>, title: "GitHub", bgColor: "bg-gray-800", neon: "#9ca3af" },
  { node: <SiNpm size={40}/>, title: "NPM", bgColor: "bg-green-500", neon: "#00c853" },
  { node: <SiReactrouter size={40}/>, title: "React Router", bgColor: "bg-yellow-500", neon: "#facc15" },
  { node: <FaMobileAlt size={40}/>, title: "Responsive", bgColor: "bg-blue-500", neon: "#2563eb" },
  { node: <SiFramer size={40}/>, title: "Framer Motion", bgColor: "bg-red-500", neon: "#ef4444" },
];

export const techLogos2 = [
  { node: <SiReact />, title: "React", bgColor: "bg-cyan-500" },
  // { node: <SiNextdotjs />, title: "Next.js", bgColor: "bg-black" },
  { node: <SiTailwindcss />, title: "Tailwind CSS", bgColor: "bg-sky-400" },
  { node: <SiJavascript />, title: "Javascript", bgColor: "bg-yellow-400" },
  { node: <SiTypescript />, title: "TypeScript", bgColor: "bg-blue-600" },
  { node: <SiHtml5 />, title: "HTML5", bgColor: "bg-orange-600" },
  { node: <SiCss />, title: "CSS3", bgColor: "bg-blue-500" },
  { node: <SiBootstrap />, title: "Bootstrap", bgColor: "bg-purple-600" },
  { node: <SiReactquery />, title: "React Query", bgColor: "bg-red-500" },
  { node: <SiAxios />, title: "Axios", bgColor: "bg-indigo-500" },
  { node: <SiRedux />, title: "Redux", bgColor: "bg-purple-500" },
  { node: <SiGit />, title: "Git", bgColor: "bg-orange-500" },
  { node: <SiGithub />, title: "GitHub", bgColor: "bg-gray-800" },
  { node: <SiNpm />, title: "NPM", bgColor: "bg-green-500" },
  { node: <SiReactrouter />, title: "React Router", bgColor: "bg-yellow-500" },
  { node: <FaMobileAlt />, title: "Responsive", bgColor: "bg-blue-500" },
  { node: <SiFramer />, title: "Framer Motion", bgColor: "bg-red-500" },
];
